[package]
name = "y2022d09"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "y2022d09"
path = "src/09.rs"

[dependencies]
aoclib = "0.2.1"
rustc-hash = "1.1"
grid = { git = "https://github.com/sncxyz/grid" }
