[package]
name = "y2022d14"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "y2022d14"
path = "src/14.rs"

[dependencies]
aoclib = "0.1.0"
grid = { git = "https://github.com/sncxyz/grid" }
rustc-hash = "1.1"
