[package]
name = "y2022d16"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "y2022d16"
path = "src/16.rs"

[dependencies]
aoclib = "0.1.0"
rustc-hash = "1.1"
search = { git = "https://github.com/sncxyz/search" }
