[package]
name = "day-18"
version = "0.1.0"
edition = "2021"

[dependencies]
aoclib = "0.1.0"
fxhash = "0.2"
grid = { git = "https://github.com/sncxyz/grid" }
search = { git = "https://github.com/sncxyz/search" }