[package]
name = "y2019d20"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "y2019d20"
path = "src/20.rs"

[dependencies]
aoclib = "0.1.0"
rustc-hash = "1.1"
grid = { git = "https://github.com/sncxyz/grid" }
search = { git = "https://github.com/sncxyz/search" }
