[package]
name = "y2019d15"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "y2019d15"
path = "src/15.rs"

[dependencies]
aoclib = "0.1.0"
intcode = { path = "../intcode" }
grid = { git = "https://github.com/sncxyz/grid " }
rustc-hash = "1.1"
