[package]
name = "y2021d13"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "y2021d13"
path = "src/13.rs"

[dependencies]
aoclib = "0.1.0"
grid = { git = "https://github.com/sncxyz/grid" }
rustc-hash = "1.1"
