[package]
name = "y2021d05"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "y2021d05"
path = "src/05.rs"

[dependencies]
aoclib = "0.1.0"
rustc-hash = "1.1"
grid = { git = "https://github.com/sncxyz/grid" }
