[package]
name = "y2023d03"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "y2023d03"
path = "src/03.rs"

[dependencies]
aoclib = "0.2.1"
grid = { git = "https://github.com/sncxyz/grid" }
rustc-hash = "1.1"
