[package]
name = "y2020d24"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "y2020d24"
path = "src/24.rs"

[dependencies]
aoclib = "0.1.0"
rustc-hash = "1.1"
grid = { git = "https://github.com/sncxyz/grid" }
